apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo-ui
  template:
    metadata:
      labels:
        app: demo-ui
spec:
  containers:
  - image: paulohenriquetrentin/demo-ui:32d614a017242db178f1c1521fff453588e22de9
  name: demo-ui
  ports:
  - containerPort: 80
